version: 2
updates:
  - package-ecosystem: "docker"
    directories:
      - "/nvim/profiles/base/*"
      - "/opencode/*"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directories:
      - "/opencode"
    schedule:
      interval: "daily"
