version: 2
updates:
  - package-ecosystem: "docker"
    # recursively searches for outdated versions in Dockerfile 
    directories:
      - "/nvim/profiles/base/Dockerfile"
      - "/opencode/Dockerfile"
    schedule:
      interval: "daily"

